/// Code generation — writes `_loom_cache/_loom_cache.typ`.
///
/// The generated file exports `#let data = ( ... )` containing all cell
/// results as a flat Typst dictionary keyed by cell id.
use crate::cache::BookCache;
use crate::config::StyleConfig;
use crate::parser::{Book, CellKind, Language};
use anyhow::{Context, Result};
use std::path::Path;

/// Write (or overwrite) `_loom_cache/_loom_cache.typ`.
pub fn write_cache_typ(cache_root: &Path, book: &Book, cache: &BookCache) -> Result<()> {
    std::fs::create_dir_all(cache_root)?;
    let out_path = cache_root.join("_loom_cache.typ");

    let mut buf = String::new();
    buf.push_str("// AUTO-GENERATED by loom — do not edit\n");
    buf.push_str("#let data = (\n");

    for cell in book.all_cells() {
        let chapter_cache = cache.chapter(&cell.chapter);
        let entry = chapter_cache.and_then(|c| c.get(&cell.id));

        let kind_str = match cell.kind {
            CellKind::Run => "run",
            CellKind::Console => "console",
            CellKind::Plot => "plot",
            CellKind::Table => "table",
            CellKind::Expr => "expr",
            CellKind::Code => "code",
            CellKind::Inline => "inline",
        };

        let lang_str = match cell.language {
            Language::Julia => "julia",
            Language::R => "r",
        };

        buf.push_str(&format!("  \"{}\": (\n", escape_typst_str(&cell.id)));
        buf.push_str(&format!("    kind: \"{}\",\n", kind_str));
        buf.push_str(&format!("    language: \"{}\",\n", lang_str));
        buf.push_str(&format!(
            "    chapter: \"{}\",\n",
            escape_typst_str(&cell.chapter)
        ));
        buf.push_str(&format!(
            "    code: \"{}\",\n",
            escape_typst_str(&cell.code)
        ));

        match entry {
            Some(e) => {
                buf.push_str(&format!(
                    "    stdout: \"{}\",\n",
                    escape_typst_str(&e.stdout)
                ));
                buf.push_str(&format!(
                    "    stderr: \"{}\",\n",
                    escape_typst_str(&e.stderr)
                ));

                buf.push_str("    figures: (");
                for (i, fig) in e.figures.iter().enumerate() {
                    if i > 0 {
                        buf.push_str(", ");
                    }
                    buf.push_str(&format!("\"{}\"", escape_typst_str(&fig.to_string_lossy())));
                }
                if e.figures.len() == 1 {
                    buf.push(',');
                }
                buf.push_str("),\n");

                match &e.error {
                    Some(err) => {
                        buf.push_str(&format!("    error: \"{}\",\n", escape_typst_str(err)))
                    }
                    None => buf.push_str("    error: none,\n"),
                }

                buf.push_str("    statements: (");
                if !e.statements.is_empty() {
                    buf.push('\n');
                    for s in &e.statements {
                        buf.push_str(&format!(
                            "      (code: \"{}\", output: \"{}\"),\n",
                            escape_typst_str(&s.code),
                            escape_typst_str(&s.output),
                        ));
                    }
                    buf.push_str("    ");
                }
                buf.push_str("),\n");

                if !e.typst_output.is_empty() {
                    buf.push_str(&format!(
                        "    typst_output: \"{}\",\n",
                        escape_typst_str(&e.typst_output)
                    ));
                } else {
                    buf.push_str("    typst_output: \"\",\n");
                }
            }
            None => {
                buf.push_str("    stdout: \"\",\n");
                buf.push_str("    stderr: \"\",\n");
                buf.push_str("    figures: (),\n");
                buf.push_str("    error: \"not yet executed\",\n");
                buf.push_str("    statements: (),\n");
                buf.push_str("    typst_output: \"\",\n");
            }
        }

        buf.push_str("  ),\n");
    }

    buf.push_str(")\n");

    std::fs::write(&out_path, &buf)
        .with_context(|| format!("Cannot write {}", out_path.display()))?;

    log::info!("Wrote {}", out_path.display());
    Ok(())
}

/// Write the data file that re-exports the cache as `_loom`.
/// Style settings from `_loom_style.typ` are inlined as `_loom_style`.
pub fn write_data_typ(data_file: &Path, cache_root: &Path) -> Result<()> {
    let cache_typ = cache_root.join("_loom_cache.typ");

    let data_dir = data_file.parent().unwrap_or(Path::new("."));
    let rel_cache = pathdiff(cache_typ.as_path(), data_dir);

    // Read the style file content to inline it.
    let style_path = data_dir.join("_loom_style.typ");
    let style_content = if style_path.exists() {
        std::fs::read_to_string(&style_path).unwrap_or_default()
    } else {
        String::new()
    };

    let content = if cache_typ.exists() {
        format!(
            "// AUTO-GENERATED by loom — do not edit\n\
             {style_content}\n\
             #import \"{}\": data as _loom\n",
            rel_cache
        )
    } else {
        format!(
            "// AUTO-GENERATED by loom — do not edit\n\
             {style_content}\n\
             // Cache not yet generated; run `loom run` first.\n\
             #let _loom = (:)\n"
        )
    };

    std::fs::write(data_file, &content)
        .with_context(|| format!("Cannot write {}", data_file.display()))?;
    log::info!("Wrote {}", data_file.display());
    Ok(())
}

fn pathdiff(target: &Path, base: &Path) -> String {
    if let Ok(target) = target.strip_prefix(base) {
        return target.to_string_lossy().to_string();
    }
    target.to_string_lossy().to_string()
}

fn escape_typst_str(s: &str) -> String {
    s.replace('\\', "\\\\")
        .replace('"', "\\\"")
        .replace('\n', "\\n")
        .replace('\r', "\\r")
        .replace('\t', "\\t")
}

/// Write `_loom_style.typ` with raw style data from `[style]` config.
/// The generated file is inlined by `_loom_data.typ`, and `loom.typ`
/// applies it through the same Julia/R module instances that render output.
pub fn write_style_typ(style: &StyleConfig, data_dir: &Path) -> Result<()> {
    let style_path = data_dir.join("_loom_style.typ");
    let mut buf = String::new();
    buf.push_str("// AUTO-GENERATED by loom from loom.toml [style] — do not edit\n");
    buf.push_str("// Import this file or let _loom_data.typ inline it automatically.\n\n");
    let entries_start = buf.len();
    buf.push_str("#let _loom_style = (\n");
    let after_open = buf.len();

    if let Some(v) = &style.jl_code_size {
        buf.push_str(&format!("  jl_code_size: {v},\n"));
    }
    if let Some(v) = &style.jl_prompt_size {
        buf.push_str(&format!("  jl_prompt_size: {v},\n"));
    }
    if let Some(v) = &style.jl_prompt_text {
        buf.push_str(&format!("  jl_prompt_text: {v},\n"));
    }
    if let Some(v) = &style.r_code_size {
        buf.push_str(&format!("  r_code_size: {v},\n"));
    }
    if let Some(v) = &style.r_prompt_size {
        buf.push_str(&format!("  r_prompt_size: {v},\n"));
    }
    if let Some(v) = &style.r_prompt_text {
        buf.push_str(&format!("  r_prompt_text: {v},\n"));
    }
    if let Some(v) = &style.output_color {
        buf.push_str(&format!("  output_color: {v},\n"));
    }
    if let Some(v) = &style.block_fill {
        buf.push_str(&format!("  block_fill: {v},\n"));
    }
    if let Some(v) = &style.block_inset {
        buf.push_str(&format!("  block_inset: {v},\n"));
    }
    if let Some(v) = &style.block_radius {
        buf.push_str(&format!("  block_radius: {v},\n"));
    }
    if let Some(v) = &style.block_stroke {
        buf.push_str(&format!("  block_stroke: {v},\n"));
    }
    if let Some(v) = &style.line_spacing {
        buf.push_str(&format!("  line_spacing: {v},\n"));
    }
    if let Some(v) = &style.caption_size {
        buf.push_str(&format!("  caption_size: {v},\n"));
    }
    if let Some(v) = &style.caption_dy {
        buf.push_str(&format!("  caption_dy: {v},\n"));
    }
    if let Some(v) = &style.caption_gap {
        buf.push_str(&format!("  caption_gap: {v},\n"));
    }
    if let Some(v) = &style.font {
        buf.push_str(&format!("  font: \"{v}\",\n"));
    }

    // If no entries were written, emit (:) for an empty dictionary (not () which is an array).
    if buf.len() == after_open {
        buf.truncate(entries_start);
        buf.push_str("#let _loom_style = (:)\n");
    } else {
        buf.push_str(")\n");
    }

    std::fs::write(&style_path, &buf)
        .with_context(|| format!("Cannot write {}", style_path.display()))?;
    log::info!("Wrote {}", style_path.display());
    Ok(())
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::config::StyleConfig;

    #[test]
    fn test_write_style_typ_empty() {
        let dir = tempfile::tempdir().unwrap();
        let style = StyleConfig::default();
        write_style_typ(&style, dir.path()).unwrap();

        let content = std::fs::read_to_string(dir.path().join("_loom_style.typ")).unwrap();
        assert!(content.contains("#let _loom_style = (:)"));
        // No style entries should appear.
        assert!(!content.contains("jl_code_size"));
        assert!(!content.contains("r_prompt_size"));
    }

    #[test]
    fn test_write_style_typ_populated() {
        let dir = tempfile::tempdir().unwrap();
        let style = StyleConfig {
            jl_prompt_size: Some("8pt".into()),
            r_code_size: Some("9pt".into()),
            block_fill: Some("luma(240)".into()),
            caption_gap: Some("0.5em".into()),
            ..Default::default()
        };
        write_style_typ(&style, dir.path()).unwrap();

        let content = std::fs::read_to_string(dir.path().join("_loom_style.typ")).unwrap();
        assert!(content.contains("jl_prompt_size: 8pt,"));
        assert!(content.contains("r_code_size: 9pt,"));
        assert!(content.contains("block_fill: luma(240),"));
        assert!(content.contains("caption_gap: 0.5em,"));
        // Fields not set should be absent.
        assert!(!content.contains("jl_code_size:"));
        assert!(!content.contains("r_prompt_text:"));
    }

    #[test]
    fn test_write_data_typ_inlines_style() {
        let dir = tempfile::tempdir().unwrap();
        let cache_dir = dir.path().join("_loom_cache");
        std::fs::create_dir_all(&cache_dir).unwrap();

        // Write a cache file so the import path is generated.
        std::fs::write(
            cache_dir.join("_loom_cache.typ"),
            "#let data = (:)\n",
        )
        .unwrap();

        // Write a style file to be inlined.
        let style = StyleConfig {
            jl_prompt_size: Some("7pt".into()),
            ..Default::default()
        };
        write_style_typ(&style, dir.path()).unwrap();

        let data_file = dir.path().join("_loom_data.typ");
        write_data_typ(&data_file, &cache_dir).unwrap();

        let content = std::fs::read_to_string(&data_file).unwrap();
        // Style dictionary should be inlined.
        assert!(content.contains("#let _loom_style = ("));
        assert!(content.contains("jl_prompt_size: 7pt,"));
        // Cache import should be present.
        assert!(content.contains("#import \"_loom_cache/_loom_cache.typ\": data as _loom"));
    }

    #[test]
    fn test_write_data_typ_without_cache() {
        let dir = tempfile::tempdir().unwrap();
        let cache_dir = dir.path().join("_loom_cache");
        // Don't create the cache dir — simulates pre-first-run state.

        let style = StyleConfig::default();
        write_style_typ(&style, dir.path()).unwrap();

        let data_file = dir.path().join("_loom_data.typ");
        write_data_typ(&data_file, &cache_dir).unwrap();

        let content = std::fs::read_to_string(&data_file).unwrap();
        assert!(content.contains("#let _loom_style = ("));
        assert!(content.contains("#let _loom = (:)"));
        // Should NOT have an import line for the missing cache.
        assert!(!content.contains("#import"));
    }

    #[test]
    fn test_style_roundtrip_from_toml() {
        let toml_str = r#"
[style]
jl_code_size = "10pt"
jl_prompt_size = "8pt"
jl_prompt_text = "\"julia> \""
r_code_size = "9pt"
r_prompt_size = "7pt"
output_color = "luma(100)"
block_fill = "luma(248)"
block_inset = "8pt"
block_radius = "2pt"
block_stroke = "0.5pt + luma(220)"
line_spacing = "0.55em"
caption_size = "12pt"
caption_dy = "1.75em"
caption_gap = "1em"
"#;

        #[derive(serde::Deserialize)]
        struct Wrapper {
            style: StyleConfig,
        }
        let wrapper: Wrapper = toml::from_str(toml_str).unwrap();

        let dir = tempfile::tempdir().unwrap();
        write_style_typ(&wrapper.style, dir.path()).unwrap();

        let content = std::fs::read_to_string(dir.path().join("_loom_style.typ")).unwrap();
        assert!(content.contains("jl_code_size: 10pt,"));
        assert!(content.contains("jl_prompt_size: 8pt,"));
        assert!(content.contains("jl_prompt_text: \"julia> \","));
        assert!(content.contains("r_code_size: 9pt,"));
        assert!(content.contains("r_prompt_size: 7pt,"));
        assert!(content.contains("output_color: luma(100),"));
        assert!(content.contains("block_fill: luma(248),"));
        assert!(content.contains("block_inset: 8pt,"));
        assert!(content.contains("block_radius: 2pt,"));
        assert!(content.contains("block_stroke: 0.5pt + luma(220),"));
        assert!(content.contains("line_spacing: 0.55em,"));
        assert!(content.contains("caption_size: 12pt,"));
        assert!(content.contains("caption_dy: 1.75em,"));
        assert!(content.contains("caption_gap: 1em,"));
    }
}
